#!/bin/bash
echo -e "\033[1;36m THIS IS YOUR INFORMATION!\033[0m"
echo ""
echo -ne "YOUR NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "YOUR KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;37mTERMUX COMMAND:\033[0m curl -sO https://raw.githubusercontent.com/Farukbrowser/sshplus-new/main/I/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;37m YOUR KEY is saved in file /root/server.pub\033[0m"
echo -e "\033[1;37mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to menu or CTRL+C to exit"
slowdns

